title: NepalFOS
email: c2edevofficial@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Leading the "Free and Open Source" movement in Nepal
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nepalfos.org" # the base hostname & protocol for your site, e.g. http://example.com
asset_base_url: /assets

google_analytics: # your google analytics id

future: true # Show blog post of future date
permalink: /blogs/:year/:month/:day/:title/

sass:
  style: compressed

# Build settings
markdown: kramdown

exclude:
  - .DS_Store
  - README.md
